### ISSUE TITLE
set/get MTU from JS

### ISSUE THREAD

**Issue by phatpaul** [liuxiaoy/cordova-plugin-bluetooth#4]
I need to know what MTU is in my JS code.
Anyway to read that?

**Comment by liuxiaoy** [comment]
the default mtu is 23.
It will be set as much as possible, no need to know current.

**Comment by phatpaul** [comment]
How do you know that I don't need to know MTU?

What if I want to transfer a large array of data ~4kB?  I should split it up into the fewest chunks of MTU size.

**Comment by liuxiaoy** [comment]
if you want set mtu yourself really,  please try
 ```
cordova plugin rm cordova-plugin-bluetooth 
cordova plugin add https://github.com/liuxiaoy/cordova-plugin-bluetooth#022fc5fb636594e741fbb7fe93b1c234c5872840
```
If there are some bugs, you can open a pull request. Thanks!

**Comment by phatpaul** [comment]
Excellent.  Thanks!
I'm testing it now and it seems to work so far...

BTW, Is the MTU setting available or needed for iOS too?  (I'm not familiar with iOS, but our product needs to support it.)

**Comment by phatpaul** [comment]
I can confirm this is working well for me.  Please consider merging it in to your next release.

**Comment by liuxiaoy** [comment]
@phatpaul Thanks for your feedback!

**Comment by phatpaul** [comment]
Now we are testing the app an iOS and it fails when call the requestMTU function.

I can see that it is only implemented for Android in this library.  https://github.com/liuxiaoy/cordova-plugin-bluetooth/commit/022fc5fb636594e741fbb7fe93b1c234c5872840

Should the function be implemented for iOS too?  Even if it is not necessary for iOS, it should still return the callback instead of failing.

**Comment by phatpaul** [comment]
Seems apple automatically negotiates MTU up to 185 during connection and doesn't allow us to change it or even see what it is.  https://forums.developer.apple.com/thread/93007

So I think I will modify in ble.js: exports.requestMtu = function(deviceOrHandle, mtu, success, fail){
to check for iOS, otherwise call the fail callback.

See PR #6

**Comment by liuxiaoy** [comment]
I agree with you. Thanks for your PR.
