### ISSUE TITLE
concurrent BLE access

### ISSUE THREAD

**Issue by phatpaul** [liuxiaoy/cordova-plugin-bluetooth#5]
I know that if I call multiple BLE functions concurrently (without sequencing on completion) I get unreliable results.  Some commands fail, some work.

I know that I should structure my code to serialize BLE commands using a pattern such as callbacks, async/await, promises, etc.

But if I didn't want to add that logic to my high-level app code, what would be a good way to ensure the commands are serialized at a lower-level?  (i.e. when the order of operations doesn't matter)

- Perhaps a semaphore that ensures only one call is operating at a time?  Calls that happen while the semaphore is busy are blocked (can JS do that?) until it is free.
- Perhaps a queue that stores pending requests (and their callbacks) and dispatches them to the BLE stack in sequence, then calls the callbacks when done? 

Is this functionality already there?  If not does it seem appropriate to add to this cordova-plugin-bluetooth?

**Comment by phatpaul** [comment]
Whoa there are a few semaphore libraries for JS:

https://github.com/kirill-konshin/mutex-promise
https://github.com/zeit/async-sema
https://github.com/jsoendermann/semaphore-async-await
https://github.com/bignerdranch/semaphorejs
https://github.com/yusukeshibata/concurrent-lock
https://github.com/devsnek/semaphore.js
https://github.com/seangenabe/mutex

**Comment by phatpaul** [comment]
Here's what I did in my application code, seems to work, and not too messy.
```c
    var chain = [];
    var chain_busy = false;
    function call_chain() {
        if (chain.length > 0) {
            chain_busy = true;
            (chain.shift())(function () { // function is shifted out and called 
                call_chain(); // with recursive argument!
            });
        } else {
            chain_busy = false;
        }
    };
```
Then in a function that can be called in any order:
```c
        chain.push(function (next) { // push a new function onto the chain
            // ... do async stuff
            ble_lib.writeCharacteristic(
                deviceHandle,
                CharHandle_ANNOUNCE,
                senddata,
                function () {
                    if (typeof cb === "function") cb();
                    // then in async's callback, insert this at the end:
                    if (typeof next === "function") next();
                },
                function (error) {
                    console.error('Error: write characteristic Annouce failed: ' + error);
                    if (typeof cb === "function") cb();
                    // then in async's callback, insert this at the end:
                    if (typeof next === "function") next();
                });
        });
        if (!chain_busy) { // a request is not already pending
            call_chain(); // start the chain
        }
```

**Comment by phatpaul** [comment]
It seems the enableNotification function doesn't have a callback when finished the enable operation!  Only callbacks for a notification recieved and for an error.
I will need this "operation finished" callback for my chaining to work, right?

```c
ble_lib.enableNotification(
            deviceHandle,
            CharHandle_ANNOUNCE,
            onNotification,
            onNotificationError)
    };
```

**Comment by liuxiaoy** [comment]
#### enableNotification operation finished if the onNotificationError not be called. The callback onNotification should be used to  receive ble data.

#### In my practice.
 I used onNotification ( func enableNotification param ) to receive all ble data.
 and send data with func writeCharacteristicWithoutResponse. 

 For the reason that this way can't support concurrent ble access.

**Comment by liuxiaoy** [comment]
@phatpaul you can make a middleware which will combination or split some ble bytes and then parse the combined bytes to the format you want.
if you want, you can put a queue which stores some requests in the middleware above. but you need to consider whether the format data and it's request consistency
